# -*- coding: utf-8 -*-
"""Olá, atualizado este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMm5z4leVe6-PRDVwD7bCuP2OzpuLEGp
"""

lista = [5,4,2]
lista[1] = 10
print(lista)

nome = 'detergente'
print(len(nome))

print(nome[0:10])

a = 10
b = 3 
a= b
c = a+b 
b = 0 
b = 0 
d = a + b
print (f' valor da variavel {c}')

n1 = 2 
n2 = 5 
n3 = 4 
if n1 < n2: 
    n3 = n1+n2
n3

sala = ['wollas', 'adryan', 'brenno', 'fabio']
print(sala[1])
a = 'wollas'
print(a[1])
nome = 'antonio'
print(nome[6])

lista = lista+[11,22,73]
print(lista)

x = 5 
x = x + 1 
x